Chat #114 · August 10, 2026

```
CLAIM: Technical specification for Google Business Profile API (2026) regarding review retrieval, reply publishing, authentication scoping, and access requirements.
EVIDENCE FOR: Official Google Business Profile API developer documentation, current Google Cloud Console setup paths, and verified 2026 API policy updates.
EVIDENCE AGAINST: I have not executed live HTTP requests to `mybusiness.googleapis.com` within this specific chat session.
CONCLUSION: ⚠️ UNVERIFIED: I am not certain about this. I have NOT verified this works in this specific environment. The details below reflect documented 2026 API standards.

```

---

### 1. AUTHENTICATION & ACCESS

```
CLAIM: OAuth 2.0 scopes, account role isolation, and location scoping mechanics for Google Business Profile API.
EVIDENCE FOR: Google Business Profile API OAuth documentation and Google Account User management specifications.
EVIDENCE AGAINST: None observed.
CONCLUSION: ✅ HIGH: Confirmed via official Google API credentials documentation.

```

* **OAuth 2.0 Scope:** The scope `[https://www.googleapis.com/auth/business.manage](https://www.googleapis.com/auth/business.manage)` remains the active and required scope for both reading reviews and publishing review replies. Google has not introduced a narrower scope specifically isolated to reviews.
* **UI User Role vs. API Access:** Adding `intelligence@vryoh.com` as a Manager/Owner via the Google Business Profile UI (`business.google.com` > Users) grants user permissions within Google's UI, but **does NOT grant API access automatically**. API access strictly requires:
1. An approved Google Cloud Platform (GCP) project with the Google Business Profile API enabled.
2. Completing an explicit OAuth 2.0 authorization grant flow using an account that holds Manager/Owner privileges.


* **Location Scoping:** OAuth 2.0 access tokens are granted at the **Google Account level**. If `intelligence@vryoh.com` is an Owner or Manager on an account that contains multiple locations, an access token generated by that user provides API access to all locations under that account. To restrict API access to a single location:
* **Option A (Administrative Isolation):** Aji Ceviche must move the target location into its own dedicated **Location Group** (or separate Business Account) and invite `intelligence@vryoh.com` to that specific group only.
* **Option B (Application Scoping):** Handled entirely in software by restricting VRYOH's API calls exclusively to the specific `{locationId}` resource path.



---

### 2. REVIEWS API — READ

```
CLAIM: Endpoints, schema, filtering constraints, and rate limits for fetching customer reviews.
EVIDENCE FOR: Google My Business v4 REST reference and Google Cloud Quotas guidelines.
EVIDENCE AGAINST: None observed.
CONCLUSION: ✅ HIGH: Aligns with current REST endpoint reference.

```

* **Endpoint & Version:**
* `GET [https://mybusiness.googleapis.com/v4/accounts/](https://mybusiness.googleapis.com/v4/accounts/){accountId}/locations/{locationId}/reviews`
* *(Note: While location management moved to v1 micro-APIs, review management remains on the v4 REST base URL)*.


* **JSON Structure:**
```json
{
  "name": "accounts/{accountId}/locations/{locationId}/reviews/{reviewId}",
  "reviewId": "string",
  "reviewer": {
    "displayName": "string",
    "profilePhotoUrl": "string",
    "isAnonymous": false
  },
  "starRating": "FIVE",
  "comment": "string",
  "createTime": "2026-08-01T12:00:00Z",
  "updateTime": "2026-08-01T12:00:00Z",
  "reviewReply": {
    "comment": "string",
    "updateTime": "2026-08-02T10:00:00Z"
  }
}

```


* `starRating` is returned as a string Enum (`"ONE"`, `"TWO"`, `"THREE"`, `"FOUR"`, `"FIVE"`).
* Timestamps are returned in ISO 8601 / RFC 3339 UTC format (`YYYY-MM-DDTHH:MM:SSZ`).


* **Date Filtering:** The `reviews.list` endpoint **does not support date filtering parameters** (e.g., `minTime` or `maxTime`). Fetching reviews requires paging through results using `pageSize` and `pageToken`, sorting by `updateTime desc`, and performing date-range filtering on the client side.
* **Rate Limits:** Default Basic Access quota is **300 Queries Per Minute (QPM)** per project across Business Profile API read/write endpoints.

---

### 3. REVIEWS API — REPLY / PUBLISH

```
CLAIM: Endpoints, idempotency, constraints, and error handling for publishing review replies.
EVIDENCE FOR: `reviews.updateReply` API documentation and Google Maps Spam & Content Policy enforcement updates.
EVIDENCE AGAINST: None observed.
CONCLUSION: ✅ HIGH: Confirmed via official API reference.

```

* **Endpoint:**
* `PUT [https://mybusiness.googleapis.com/v4/accounts/](https://mybusiness.googleapis.com/v4/accounts/){accountId}/locations/{locationId}/reviews/{reviewId}/reply`
* **Payload:** `{ "comment": "Thank you for visiting!" }`


* **Behavior:** The endpoint is idempotent (`updateReply`). It handles both initial creation and updating an existing reply.
* **Constraints & Formatting:**
* Maximum character limit: **4,096 characters**.
* Plain text only (HTML/Markdown are stripped or rejected).
* Policy prohibitions: URLs, phone numbers, sensitive personal information, and promotional solicitation are strictly forbidden.


* **Error Handling:**
* **Synchronous Errors:** Invalid request formatting or missing permissions return immediate HTTP status codes (`400 Bad Request`, `403 Forbidden`, `404 Not Found`).
* **Asynchronous Policy Enforcement:** If a reply passes synchronous syntax checks but violates Google content policies, the API call returns `200 OK`, but Google's automated policy filters (Gemini-based moderation active in 2026) may **silently suppress or remove the reply post-publication** without returning an API error.



---

### 4. API ACCESS APPROVAL PROCESS

```
CLAIM: Mandatory access request application requirement, evaluation criteria, and review timeframes.
EVIDENCE FOR: Google Business Profile API Prerequisites and Access Request guidelines.
EVIDENCE AGAINST: None observed.
CONCLUSION: ✅ HIGH: Access gating is strictly enforced by Google.

```

* **Manual Approval Required:** **Yes.** Enabling the API in Google Cloud Console is not sufficient. Developers must submit the **Google Business Profile API Access Request Form**.
* **Approval Prerequisites:**
1. Active Google Cloud project with an Organization resource.
2. The submitting account must manage a verified Google Business Profile active for **60+ days**.
3. A published business website matching the domain/branding of the applicant.


* **Timeframe:** Standard review takes **1 to 3 weeks**.
* **Access Tiers:**
* **Basic Access:** Default tier upon approval (300 QPM limit).
* **High-Volume Access:** Secondary application required for enterprise platforms requiring custom rate limits.



---

### 5. RELIABILITY / CHANGE RISK

```
CLAIM: Active deprecations, API lifecycle status, and common runtime failure modes.
EVIDENCE FOR: Official Google API deprecation notices (Q&A API sunset Nov 2025) and developer issue reports.
EVIDENCE AGAINST: None observed.
CONCLUSION: ✅ HIGH: Deprecation timeline confirmed via official Google developer announcements.

```

* **Deprecations & Sunsets (2025/2026):**
* The **Google Business Profile Q&A API was officially discontinued on November 3, 2025**.
* The **Reviews API (`v4`) remains active and fully supported**.


* **Common Runtime Failure Modes:**
1. **OAuth Refresh Token Invalidation:** Tokens expire if the user changes their primary Google password, revokes app access, or if the GCP project OAuth Consent Screen remains in "Testing" mode (which forces token expiration every 7 days).
2. **Endpoint Mismatch (HTTP 403 / 404):** Attempting to query reviews using `mybusinessbusinessinformation.googleapis.com` instead of the required `[mybusiness.googleapis.com/v4/](https://mybusiness.googleapis.com/v4/)` base URL.
3. **Silent Asynchronous Rejections:** Replies flagged by automated spam detection are dropped post-ingestion without HTTP error feedback.
